```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(shiny)
library(maps)
library(scales)
library(tsibble)
library(dplyr)
```

```{r, message=FALSE}
# state population data
state_pop_2022 = read_csv("https://uwmadison.box.com/shared/static/z4zms2iesc8rr6lov8x3p74or2q7syyp.csv") %>% 
  mutate(`Population` = `Population`*1e6)

# number of hospitals/state
hospitals <- read_csv("https://uwmadison.box.com/shared/static/pywujigfcjq83ka272igh6j1kn03ssqv.csv") %>%
  mutate(State = str_remove(State, "^\\w+\\s+-\\s+")) %>% # remove "abbrev -" from State col
  left_join(state_pop_2022) %>%  # join state population data set
  mutate(`People Per Hospital` = `Population` / `Number Hospitals`) %>% # create new people per hospital col
  mutate(State = tolower(State)) %>%  # make the state name lower case
  drop_na() %>%  #remove missing values
  select(`State`, `People Per Hospital`, `Number Hospitals`, `Staffed Beds`, `Total Discharges`) # change ordering
  
# head(hospitals)
```

```{r, message=FALSE}
# education PPCS per state
education_spending_ppcs <- read_csv("https://uwmadison.box.com/shared/static/abtigdtpzkckdh4ivcx5vftck9uyov30.csv") %>% 
  rename(State = `Geographic area`) %>% 
  select(`State`, `PPCS`) %>% 
  drop_na() %>% 
  mutate(State = gsub("\\.", "", State)) %>%
  mutate(State = tolower(State))             
# head(education_spending_ppcs)
```


```{r}
# Realtor.com per state data set
realty_data <- read_csv("https://uwmadison.box.com/shared/static/r9kw6nyro7n0p3dr40q0zn7g3eyaw490.csv") %>% 
  mutate(month = as.Date(paste0(realty_data$month, "01"), format = "%Y%m%d")) %>% 
  mutate(date = as.Date(paste0(realty_data$month_date_yyyymm, "01"), format = "%Y%m%d")) %>% # new
  mutate(year = format(realty_data$date, "%Y")) %>% # new
  mutate(format(realty_data$date, "%Y")) %>%
  rename(State= state) %>% 
  mutate(State = tolower(State)) 

head(realty_data)

median_listing_price <- realty_data %>% 
  filter(month_date_yyyymm == 202301) %>% 
  select(State, median_listing_price)
median_listing_price

median_listing_days <- realty_data %>% 
  filter(month_date_yyyymm == 202301) %>% 
  select(State, median_days_on_market)
median_listing_days

head(realty_data)
filtered_data <- realty_data %>%
    group_by(State) %>% 
    filter(State == "wisconsin")

filtered_data$month <- as.Date(paste0(filtered_data$month_date_yyyymm, "01"), format = "%Y%m%d")
create_median_days_plot(filtered_data)
```


```{r}
# Function for creating map plot
create_map_plot <- function(map_data, fill_var, title, low_is_good) {
  par(mar = c(0, 0, 0, 0))
  ggplot(map_data, aes(x = long, y = lat, group = group, fill = !!sym(fill_var))) +
    geom_polygon(color = "white") +
    scale_fill_gradientn(
      colors = if (low_is_good) c("darkgreen", "green", "yellow", "orange", "red", "darkred")
                else c("darkred", "red", "orange", "yellow", "green", "darkgreen"),
      guide = guide_colorbar(
        title = title,
        ticks = FALSE,
        barwidth = 3          
      )
    ) +
    coord_quickmap() +
    theme_void()
}
```

```{r}
create_median_price_plot <- function(data){
  ggplot(data, aes(x = date, y = median_listing_price, group = State, color = State)) +
  geom_line() +
  labs(title = "Median Home Prices Over Time by State",
       x = "Year",
       y = "Median Home Price")+
  theme(legend.position = "none")
}
```

```{r}
create_median_days_plot <- function(data){
  ggplot(data, aes(x = month, y = median_days_on_market)) +
    geom_line() +
    scale_x_date(breaks = "1 year", date_labels = "%Y%M") +
    facet_wrap(~State) +
    labs(x = "Year", y = "median_days_on_market") +
    ggtitle("Seasonal Plot of Median listing Price")+
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5))
}
```



```{r}
# Define UI
ui <- fluidPage(
  tags$h1("Click on a US state"),
  tags$style(HTML("
    #us_map {
      float: center;
    }
    #state_data {
      width: 100%;
      overflow-x: auto;
      margin-top: 20px;
    }
  ")),
  sidebarLayout(
    sidebarPanel(
      h5("Instructions"),
      p("Click on a state to select it as input."),
      hr(),
      verbatimTextOutput("selected_state"),
      uiOutput("map_var_input"),
      actionButton("clear_selection_button", "Clear Selection"),
      br(),
      fluidRow(
        column(
          width = 12,
          dataTableOutput("state_data")
        )
      )
      
    ),
    mainPanel(
      plotOutput("us_map", click = "plot_click", width = "700px", height = "600px"),
      plotOutput("median_price_plot", width = "500px", height = "400px"),
      plotOutput("median_days_plot", width = "500px", height = "400px")
    )
  )
)


# Define server
server <- function(input, output, session) {
  
  observeEvent(input$clear_selection_button, {
    selected_state$state <- NULL
    updateSelectInput(session, "plot_click", selected = NULL)
  })
  
  # Create US map
  output$us_map <- renderPlot({
    # If the "Education Spending" option is selected, color the states based on the Total column
    if (input$map_var == "Education Spending") {
      map_data <- map_data("state", exact = FALSE) %>%
        left_join(education_spending_ppcs, by = c("region" = "State")) %>% 
        mutate(fill_color = PPCS / 1e3)
      create_map_plot(map_data, "fill_color", "Total (thousands)", FALSE)
    } 
    else if (input$map_var == "# Citizens Per Hospital") {
      map_data <- map_data("state", exact = FALSE) %>%
        left_join(hospitals, by = c("region" = "State")) %>% 
        mutate(fill_color = `People Per Hospital` / 1e3)
      create_map_plot(map_data, "fill_color", "Total (thousands)", TRUE)
    }
    else if (input$map_var == "Median Home Prices"){
      map_data <- map_data("state", exact = FALSE) %>%
        # left_join(realty_data, by = c("region" = "State")) %>%
        left_join(median_listing_price, by = c("region" = "State")) %>% 
        mutate(fill_color = median_listing_price / 1e3)
      create_map_plot(map_data, "fill_color", "Total (thousands)", TRUE)
    } else if (input$map_var == "Median Days on the Market"){
       map_data <- map_data("state", exact = FALSE) %>%
        left_join(median_listing_days, by = c("region" = "State")) %>% 
        mutate(fill_color = median_days_on_market)
      create_map_plot(map_data, "fill_color", "Median Listing Days", TRUE)
    }
    
  })
  
  # Create reactive value for selected (clicked) state
  selected_state <- reactiveValues(state = NULL)
  
  # Update selected state when user clicks on map by x and y coordinates
  observeEvent(input$plot_click, {
    click_loc <- input$plot_click
    state_name <- map.where("state", click_loc$x, click_loc$y)
    state_name <- gsub(":.*", "", state_name) # remove any characters after and including ":"
    selected_state$state <- state_name
  })
  
  # Display selected state in sidebar with uppercase first letter
  output$selected_state <- renderPrint({
    if (!is.null(selected_state$state)) {
      paste0("Selected state: ", str_to_title(selected_state$state))
    } else {
      "Please click on a state."
    }
  })
  
  # Render education spending data table
  output$state_data <- renderDataTable({
    if (!is.null(selected_state$state)) {
      if (input$map_var == "Education Spending") {
        education_spending_ppcs %>% 
          filter(State == selected_state$state) %>%
          mutate(State = str_to_title(State)) %>% 
          mutate(PPCS = comma(PPCS))
        
      } else if (input$map_var == "# Citizens Per Hospital") {
        hospitals %>% 
          filter(State == selected_state$state) %>%
          mutate(State = str_to_title(State)) %>% 
          mutate(PPCS = comma(`People Per Hospital`))
      } else if (input$map_var == "Median Home Prices"){
        realty_data %>%
          filter(State == selected_state$state) %>% 
          mutate(State = str_to_title(State)) %>%
          mutate(month_date_yyyymm = format(as.Date(paste0(month_date_yyyymm, "01"), format = "%Y%m%d"), "%B %Y")) %>% 
          select(`month_date_yyyymm`,`median_listing_price`, `median_listing_price_per_square_foot`, `median_listing_price_mm`, `median_listing_price_yy`)
      } else if (input$map_var == "Median Days on the Market"){
        realty_data %>%
          filter(State == selected_state$state) %>% 
          mutate(State = str_to_title(State)) %>%
          mutate(month_date_yyyymm = format(as.Date(paste0(month_date_yyyymm, "01"), format = "%Y%m%d"), "%B %Y")) %>% 
          select(`month_date_yyyymm`,`median_days_on_market`, `median_days_on_market_mm`, `median_days_on_market_yy`)
      }
        
    } else {
      NULL
    }
  })
  
  # Median House Prices Over Time Plot
  output$median_price_plot <- renderPlot({
    if (input$map_var == "Median Home Prices") {
      if (is.null(selected_state$state)) {
        filtered_data <- realty_data
      } else {
        filtered_data <- realty_data %>%
          filter(State == selected_state$state)
      }
      create_median_price_plot(filtered_data)
    }else{
      NULL
    }
  })
  
  output$median_days_plot <- renderPlot({
    if (input$map_var == "Median Days on the Market") {
      if (!is.null(selected_state$state)) {
        # filtered_data$month <- as.Date(paste0(filtered_data$month_date_yyyymm, "01"), format = "%Y%m%d")

        filtered_data <- realty_data %>%
          group_by(State) %>% 
          filter(State == selected_state$state)
          
        filtered_data$month <- as.Date(paste0(filtered_data$month_date_yyyymm, "01"), format = "%Y%m%d")
        create_median_days_plot(filtered_data)
      } else {
       NULL 
      }
      
    }else{
      NULL
    }
  })
  
  # Create input for selecting map color
  output$map_var_input <- renderUI({
    selectInput("map_var", "Select a variable:", choices = c("Select", "Education Spending", "# Citizens Per Hospital", "Median Home Prices", "Median Days on the Market"))
  })
  
}

# Run the app
shinyApp(ui = ui, server = server)
```